version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls-votes
    volumes:
      - polls_votes_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - 'polls_votes_redis_data:/bitnami/redis/data'
  

volumes:
  polls_votes_pg_data:
  polls_votes_redis_data:
